/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DailyRouteImport } from './routes/daily'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as MoodRouteImport } from './routes/mood'
import { Route as RequestRouteImport } from './routes/request'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StreakRouteImport } from './routes/streak'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksIdRouteImport } from './routes/books/$id'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsIdRouteImport } from './routes/collections/$id'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibraryIdRouteImport } from './routes/library/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyRoute = DailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const MoodRoute = MoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakRoute = StreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIdRoute = LibraryIdRouteImport.update({
  id: '/library/$id',
  path: '/library/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/daily': typeof DailyRoute
  '/gallery': typeof GalleryRoute
  '/mood': typeof MoodRoute
  '/request': typeof RequestRoute
  '/settings': typeof SettingsRoute
  '/streak': typeof StreakRoute
  '/study': typeof StudyRoute
  '/submit': typeof SubmitRoute
  '/vault': typeof VaultRoute
  '/books/$id': typeof BooksIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/books/': typeof BooksIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/daily': typeof DailyRoute
  '/gallery': typeof GalleryRoute
  '/mood': typeof MoodRoute
  '/request': typeof RequestRoute
  '/settings': typeof SettingsRoute
  '/streak': typeof StreakRoute
  '/study': typeof StudyRoute
  '/submit': typeof SubmitRoute
  '/vault': typeof VaultRoute
  '/books/$id': typeof BooksIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/books': typeof BooksIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/library': typeof LibraryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/daily': typeof DailyRoute
  '/gallery': typeof GalleryRoute
  '/mood': typeof MoodRoute
  '/request': typeof RequestRoute
  '/settings': typeof SettingsRoute
  '/streak': typeof StreakRoute
  '/study': typeof StudyRoute
  '/submit': typeof SubmitRoute
  '/vault': typeof VaultRoute
  '/books/$id': typeof BooksIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/library/$id': typeof LibraryIdRoute
  '/books/': typeof BooksIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/library/': typeof LibraryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/daily'
    | '/gallery'
    | '/mood'
    | '/request'
    | '/settings'
    | '/streak'
    | '/study'
    | '/submit'
    | '/vault'
    | '/books/$id'
    | '/collections/$id'
    | '/library/$id'
    | '/books/'
    | '/collections/'
    | '/library/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/daily'
    | '/gallery'
    | '/mood'
    | '/request'
    | '/settings'
    | '/streak'
    | '/study'
    | '/submit'
    | '/vault'
    | '/books/$id'
    | '/collections/$id'
    | '/library/$id'
    | '/books'
    | '/collections'
    | '/library'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/daily'
    | '/gallery'
    | '/mood'
    | '/request'
    | '/settings'
    | '/streak'
    | '/study'
    | '/submit'
    | '/vault'
    | '/books/$id'
    | '/collections/$id'
    | '/library/$id'
    | '/books/'
    | '/collections/'
    | '/library/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DailyRoute: typeof DailyRoute
  GalleryRoute: typeof GalleryRoute
  MoodRoute: typeof MoodRoute
  RequestRoute: typeof RequestRoute
  SettingsRoute: typeof SettingsRoute
  StreakRoute: typeof StreakRoute
  StudyRoute: typeof StudyRoute
  SubmitRoute: typeof SubmitRoute
  VaultRoute: typeof VaultRoute
  BooksIdRoute: typeof BooksIdRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  LibraryIdRoute: typeof LibraryIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily': {
      id: '/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mood': {
      id: '/mood'
      path: '/mood'
      fullPath: '/mood'
      preLoaderRoute: typeof MoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak': {
      id: '/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof StreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$id': {
      id: '/library/$id'
      path: '/library/$id'
      fullPath: '/library/$id'
      preLoaderRoute: typeof LibraryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DailyRoute: DailyRoute,
  GalleryRoute: GalleryRoute,
  MoodRoute: MoodRoute,
  RequestRoute: RequestRoute,
  SettingsRoute: SettingsRoute,
  StreakRoute: StreakRoute,
  StudyRoute: StudyRoute,
  SubmitRoute: SubmitRoute,
  VaultRoute: VaultRoute,
  BooksIdRoute: BooksIdRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  LibraryIdRoute: LibraryIdRoute,
  BooksIndexRoute: BooksIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
