/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksIdRouteImport } from './routes/books/$id'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as CollectionsIdRouteImport } from './routes/collections/$id'
import { Route as MusingsIndexRouteImport } from './routes/musings/index'
import { Route as MusingsIdRouteImport } from './routes/musings/$id'
import { Route as PoemsIndexRouteImport } from './routes/poems/index'
import { Route as PoemsIdRouteImport } from './routes/poems/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIdRoute = BooksIdRouteImport.update({
  id: '/books/$id',
  path: '/books/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MusingsIndexRoute = MusingsIndexRouteImport.update({
  id: '/musings/',
  path: '/musings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MusingsIdRoute = MusingsIdRouteImport.update({
  id: '/musings/$id',
  path: '/musings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsIndexRoute = PoemsIndexRouteImport.update({
  id: '/poems/',
  path: '/poems/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoemsIdRoute = PoemsIdRouteImport.update({
  id: '/poems/$id',
  path: '/poems/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit': typeof SubmitRoute
  '/books/$id': typeof BooksIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/musings/$id': typeof MusingsIdRoute
  '/poems/$id': typeof PoemsIdRoute
  '/books/': typeof BooksIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/musings/': typeof MusingsIndexRoute
  '/poems/': typeof PoemsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit': typeof SubmitRoute
  '/books/$id': typeof BooksIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/musings/$id': typeof MusingsIdRoute
  '/poems/$id': typeof PoemsIdRoute
  '/books': typeof BooksIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/musings': typeof MusingsIndexRoute
  '/poems': typeof PoemsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/submit': typeof SubmitRoute
  '/books/$id': typeof BooksIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/musings/$id': typeof MusingsIdRoute
  '/poems/$id': typeof PoemsIdRoute
  '/books/': typeof BooksIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/musings/': typeof MusingsIndexRoute
  '/poems/': typeof PoemsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/submit'
    | '/books/$id'
    | '/collections/$id'
    | '/musings/$id'
    | '/poems/$id'
    | '/books/'
    | '/collections/'
    | '/musings/'
    | '/poems/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/submit'
    | '/books/$id'
    | '/collections/$id'
    | '/musings/$id'
    | '/poems/$id'
    | '/books'
    | '/collections'
    | '/musings'
    | '/poems'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/submit'
    | '/books/$id'
    | '/collections/$id'
    | '/musings/$id'
    | '/poems/$id'
    | '/books/'
    | '/collections/'
    | '/musings/'
    | '/poems/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SubmitRoute: typeof SubmitRoute
  BooksIdRoute: typeof BooksIdRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  MusingsIdRoute: typeof MusingsIdRoute
  PoemsIdRoute: typeof PoemsIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  MusingsIndexRoute: typeof MusingsIndexRoute
  PoemsIndexRoute: typeof PoemsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$id': {
      id: '/books/$id'
      path: '/books/$id'
      fullPath: '/books/$id'
      preLoaderRoute: typeof BooksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musings/': {
      id: '/musings/'
      path: '/musings'
      fullPath: '/musings/'
      preLoaderRoute: typeof MusingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musings/$id': {
      id: '/musings/$id'
      path: '/musings/$id'
      fullPath: '/musings/$id'
      preLoaderRoute: typeof MusingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/': {
      id: '/poems/'
      path: '/poems'
      fullPath: '/poems/'
      preLoaderRoute: typeof PoemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poems/$id': {
      id: '/poems/$id'
      path: '/poems/$id'
      fullPath: '/poems/$id'
      preLoaderRoute: typeof PoemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SubmitRoute: SubmitRoute,
  BooksIdRoute: BooksIdRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  MusingsIdRoute: MusingsIdRoute,
  PoemsIdRoute: PoemsIdRoute,
  BooksIndexRoute: BooksIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  MusingsIndexRoute: MusingsIndexRoute,
  PoemsIndexRoute: PoemsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
